[color-theme]
name = "Milk Tea"

[color-theme.base]
white = "#F7F5E8"
black = "#281E1B"
grey = "#DACCA9"
blue = "#1D6795"
red = "#C4455A"
yellow = "#E3BE35"
orange = "#D79B42"
green = "#9CD06C"
purple = "#9D77C5"
cyan = "#20AC89"
magenta = "#DE96D7"

[color-theme.syntax]
attribute = "$yellow"
builtinType = "$cyan"
comment = "$grey"
constant = "$red"
constructor = "$orange"
embedded = "$cyan"
enum = "$yellow"
enum-member = "$red"
enumMember = "$red"
escape = "$cyan"
field = "$red"
function = "$blue"
"function.method" = "$blue"
interface = "$yellow"
keyword = "$purple"
"keyword.control" = "$purple"
method = "$red"
number = "$red"
property = "$red"
"punctuation.delimiter" = "$yellow"
selfKeyword = "$purple"
string = "$green"
"string.escape" = "$green"
struct = "$yellow"
structure = "$yellow"
symbol = "$yellow"
tag = "$blue"
"text.reference" = "$yellow"
"text.title" = "$orange"
"text.uri" = "$cyan"
type = "$orange"
"type.builtin" = "$magenta"
typeAlias = "$yellow"
variable = "$black"
"variable.other.member" = "$green"

[color-theme.ui]
"activity.background" = "$grey"
"activity.current" = "$white"
"completion.background" = "$magenta"
"completion.current" = "$green"
"completion_lens.foreground" = "$black"
"editor.background" = "$white"
"editor.caret" = "$black"
"editor.current_line" = "#F9E7B8"
"editor.dim" = "#DACCA9"
"editor.drag_drop_background" = "#9CD06C33"
"editor.drag_drop_tab_background" = "#9CD06C33"
"editor.focus" = "#000000"
"editor.foreground" = "#7E5026"
"editor.indent_guide" = "$grey"
"editor.link" = "$blue"
"editor.selection" = "#7E5026"
"editor.sticky_header_background" = "$white"
"editor.visible_whitespace" = "$grey"
"error_lens.error.background" = "#E4564920"
"error_lens.error.foreground" = "$red"
"error_lens.other.background" = "#A0A1A720"
"error_lens.other.foreground" = "#A0A1A7"
"error_lens.warning.background" = "#C1840120"
"error_lens.warning.foreground" = "$yellow"
"hover.background" = "#EAEAEB"
"inlay_hint.background" = "#528bFF55"
"inlay_hint.foreground" = "$black"
"lapce.border" = "#7E5026"
"lapce.button.primary.background" = "$magenta"
"lapce.button.primary.foreground" = "$white"
"lapce.dropdown_shadow" = "#B4B4B4"
"lapce.error" = "#E51400"
"lapce.icon.active" = "$black"
"lapce.icon.inactive" = "#7E5026"
"lapce.plugin.author" = "#707070"
"lapce.plugin.description" = "$black"
"lapce.plugin.name" = "#444444"
"lapce.remote.connected" = "$green"
"lapce.remote.connecting" = "$cyan"
"lapce.remote.disconnected" = "$magenta"
"lapce.remote.icon" = "$white"
"lapce.remote.local" = "$black"
"lapce.scroll_bar" = "#F9E7B8"
"lapce.tab.active.background" = "$grey"
"lapce.tab.active.foreground" = "$black"
"lapce.tab.active.underline" = "$black"
"lapce.tab.inactive.background" = "#7E5026"
"lapce.tab.inactive.foreground" = "$grey"
"lapce.tab.inactive.underline" = "$grey"
"lapce.tab.separator" = "$black"
"lapce.warn" = "$red"
"markdown.blockquote" = "#686868"
"palette.background" = "$white"
"palette.current.background" = "$black"
"palette.current.foreground" = "$white"
"palette.foreground" = "$black"
"panel.background" = "$grey"
"panel.current.background" = "$green"
"panel.current.foreground" = "$white"
"panel.current.foreground.dim" = "#A0A1A7"
"panel.foreground" = "$black"
"panel.foreground.dim" = "#7E5026"
"panel.hovered.background" = "$magenta"
"panel.hovered.foreground" = "$black"
"panel.hovered.foreground.dim" = "#A0A1A7"
"source_control.added" = "$green"
"source_control.modified" = "$cyan"
"source_control.removed" = "$magenta"
"status.background" = "#EAEAEB"
"status.foreground" = "$black"
"status.modal.insert.background" = "$red"
"status.modal.insert.foreground" = "$white"
"status.modal.normal.background" = "$blue"
"status.modal.normal.foreground" = "$white"
"status.modal.terminal.background" = "$purple"
"status.modal.terminal.foreground" = "$white"
"status.modal.visual.background" = "$yellow"
"status.modal.visual.foreground" = "$white"
"terminal.background" = "$white"
"terminal.black" = "$black"
"terminal.blue" = "$blue"
"terminal.bright_black" = "#A0A1A7"
"terminal.bright_blue" = "$blue"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_green" = "$green"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_red" = "$red"
"terminal.bright_white" = "#090A0B"
"terminal.bright_yellow" = "$yellow"
"terminal.cursor" = "$black"
"terminal.cyan" = "$cyan"
"terminal.foreground" = "$black"
"terminal.green" = "$green"
"terminal.magenta" = "$magenta"
"terminal.red" = "$red"
"terminal.white" = "$white"
"terminal.yellow" = "$yellow"

[ui]
font-family = ""
font-size = 13
icon-size = 0
header-height = 35
status-height = 25
tab-min-width = 100
scroll-width = 10
drop-shadow-width = 0
preview-editor-width = 0
hover-font-family = ""
hover-font-size = 0
trim-search-results-whitespace = true
list-line-height = 25
