# volt.toml (Lapce plugin definition)
name = "milk-tea"
display-name = "Milk Tea"
description = "WIP theme based around bubble milk tea in its many forms"
version = "0.0.1"
author = "wpkelso"
repository = "wpkelso/milk-tea-lapce-theme"
themes = ["milk-tea.toml"]
