# volt.toml (Lapce plugin definition)
name = "milk-tea"
display-name = "Milk Tea"
description = "Theme based around milk tea in its many forms"
icon = "assets/logo.png"
version = "0.0.2"
author = "wpkelso"
repository = "wpkelso/milk-tea-lapce-theme"
color-themes = ["milk-tea.toml"]
