name = "milk-tea"
display-name = "Milk Tea"
description = "WIP theme based around bubble milk tea in its many forms"
version = "A1"
author = "wpkelso"
repository = "https://github.com/wpkelso/milk-tea"
themes = ["milk-tea.toml"]
